spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignmentdb
    username: ${DB_USER:genesis}
    password: ${DB_PASS:genesis}

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9093


jwt:
  secret: ${JWT_SECRET:2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D}

# redis configuration
#  redis:
#    host: localhost
#  redis:
#    port: 6379